name: 'Awesome parse action'
description: 'Parse awesome links to bookmarks'

inputs:
  type:
    description: 'Choose output type <csv|json|bookmarks>'
    required: false
    default: 'bookmarks'
  commit_message:
    description: 'Commit message'
    required: false
    default: 'Exports "${{ inputs.input }}" to "${{ inputs.output }}"'
  commit_branch:
    description: 'Commit branch'
    required: false
    default: 'main'
  input:
    description: 'Input file path'
    required: false
    default: 'README.md'
  output:
    description: 'Output file path'
    required: false
    default: 'bookmarks.html'    

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  
    - run: mkdir -p $(dirname "${{ inputs.output }}")
      shell: bash
    - run: | 
        ${{ github.action_path }}/index.sh -b "${{ github.action_path }}" -t ${{ inputs.type }} < "${{ inputs.input }}" > "${{ inputs.output }}"
      shell: bash
    - uses: EndBug/add-and-commit@v7
      with:
        message: "${{ inputs.commit_message }}"
        default_author: github_actions
        branch: "${{ inputs.commit_branch }}"

branding:
  icon: star
  color: purple